### ISSUE TITLE
Is this Just supposed to be anonymous to the clients?

### ISSUE THREAD

**Issue by IamNotHuman** [z-------------/Abungo#1]
The decryption says "Simple anonymous chat with node.js and Socket.IO", but on the server side I can print the whole socket which displays the username, IP address, Port, etc. making it not a Anonymous chat

**Comment by z-------------** [comment]
That is correct. Regardless of how the application is written, it's inevitable for the server to know what IPs are connecting to it unless the user is behind a VPN or something. In any case, I wrote Abungo mostly as a way to experiment with Node and Socket.io and not really meant for production use.
